# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TeamTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'MaterialComponents/Buttons'
pod 'MaterialComponents/Buttons+Theming'
pod 'MaterialComponents/Dialogs'
pod 'MaterialComponents/Tabs+TabBarView'
pod 'MaterialComponents/Tabs+TabBarViewTheming'
pod 'MaterialComponents/Snackbar'

end
